create database basic_case_study



/**********DATA PREPARATION*********/

--Total number of rows for each 3 tables
SELECT
count(*)
FROM 
Customer

SELECT
count(*)
FROM 
prod_cat_info

SELECT
count(*)
FROM 
Transactions

--Total number of transactions that have returned 

SELECT
*
FROM
Transactions
WHERE
total_amt LIKE '-%'

--Converting the dates into date format

select convert(date, DOB, 105) as DOB from Customer
select convert(date, tran_date,105) AS DATES from Transactions

--Time range of transactions 

SELECT DATEDIFF(YEAR, MIN(CONVERT(DATE, TRAN_DATE, 105)),MAX(CONVERT(DATE, TRAN_DATE, 105))) AS YEARS,
DATEDIFF(MONTH, MIN(CONVERT(DATE, TRAN_DATE, 105)),MAX(CONVERT(DATE, TRAN_DATE, 105))) AS MONTHS,
DATEDIFF(DAY, MIN(CONVERT(DATE, TRAN_DATE, 105)),MAX(CONVERT(DATE, TRAN_DATE, 105))) AS DAYS
FROM
TRANSACTIONS

--Which category does sub-category 'DIY' belongs to?

SELECT
prod_cat
FROM
prod_cat_info
WHERE
prod_subcat = 'DIY'

/***************DATA ANALYSIS***************/

--Q1. Which channel is most frequently used for transactions?

select top 1

SELECT 
Store_type, COUNT(STORE_TYPE) AS CNT
FROM
Transactions
GROUP BY
Store_type
ORDER BY
CNT DESC;

--Q2. What is the count of male and female customers in the database?

SELECT
GENDER, COUNT(GENDER) AS CNT
FROM
Customer
WHERE
GENDER IN ('M','F')
GROUP BY
Gender

--Q3. From which city do we have the maximum number of customer and how many?

SELECT TOP 1
city_code, COUNT(CUSTOMER_ID) AS CNT
FROM
Customer
GROUP BY
city_code
ORDER BY
CNT DESC

--Q4. how many sub-categories are there under the books category?

SELECT
prod_cat, PROD_SUBCAT, COUNT(PROD_SUBCAT) AS CNT
FROM
prod_cat_info
WHERE
prod_cat IN('BOOKS')
GROUP BY
prod_cat, PROD_SUBCAT

--Q5. What is the max qty of product ever ordered?

SELECT TOP 1
prod_cat, COUNT(QTY) AS CNT
FROM
prod_cat_info A
INNER JOIN Transactions B ON A.prod_cat_code = B.prod_cat_code AND A.prod_sub_cat_code = B.prod_subcat_code
GROUP BY
prod_cat
ORDER BY
CNT DESC;

--Q6. what is net total revenue generated in categories electronics and books?

SELECT 
prod_cat, ROUND(SUM(CAST(total_amt AS float)),2) AS TOTAL 
FROM
prod_cat_info A
INNER JOIN Transactions B ON A.prod_cat_code = B.prod_cat_code AND A.prod_sub_cat_code = B.prod_subcat_code
WHERE
prod_cat IN ('CLOTHING' , 'ELECTRONICS')
GROUP BY
prod_cat
union all
select
'Net total revenue' as col1, round(sum(cast(total_amt as float)),2) from Transactions where prod_cat_code in (3,5);

--Q7. How many customers have >10 transactions with us, excluding returns?

SELECT
cust_id,COUNT(transaction_id) AS CNT
FROM
Transactions
WHERE
CAST(total_amt AS float)>0
GROUP BY
cust_id
HAVING 
COUNT(transaction_id)>10

--Q8. What is combined revenue earned from elecronics and clothing, from flagship stores?

SELECT 
Store_type, ROUND(SUM(CAST(total_amt AS float)),2) AS TOTAL 
FROM
prod_cat_info A
INNER JOIN Transactions B ON A.prod_cat_code = B.prod_cat_code AND A.prod_sub_cat_code = B.prod_subcat_code
WHERE
prod_cat IN ('CLOTHING' , 'ELECTRONICS') AND
Store_type = 'FLAGSHIP STORE'
GROUP BY
Store_type

--Q9. What is the total revenue generated from male customers in electronics category? output should display total revenue by prod-subcat?

SELECT
prod_cat, ROUND(SUM(CAST(total_amt AS float)),2) AS TOTAL_REVENUE
FROM
Customer A
INNER JOIN Transactions B ON A.customer_Id = B.cust_id
INNER JOIN prod_cat_info C ON B.prod_cat_code = C.prod_cat_code AND B.prod_subcat_code = C.prod_sub_cat_code
WHERE
Gender = 'M' AND prod_cat = 'ELECTRONICS'
GROUP BY
prod_cat;

--Q10. what is the percent of sales and return by product sub category; display on top 5 sub categories in terms of sales?


select top 5
prod_subcat,
round((sum(case when total_amt>0 then total_amt else 0 end)/(sum(total_amt )))*100,2) as sales_percent,

round((sum(case when total_amt<0 then total_amt else 0 end)/(sum(total_amt)))*100,2) as return_percent
from transactions A
inner join prod_cat_info B on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
group by
prod_subcat
order by
sales_percent desc , return_percent;

--Q11. For all customer aged between 25 and 35 years find what is the net total revenue generated by these customers in last 30 days of transactions from max transaction date?


select
round(sum(cast(total_amt as float)),2) as net_revenue
from( select *,MAX(convert(date,tran_date,105)) over () as max_tran_date
from
Transactions) t
inner join Customer on cust_id = customer_Id
where
convert(date,tran_date,105)>= DATEADD(day,-30,max_tran_date) and
convert(date,tran_date,105)>= DATEADD(year,25,convert(date,dob,105)) and
convert(date,tran_date,105)< DATEADD(year,36,convert(date,dob,105));



--Q12. Which product category has seen the max value of return in the last 3 months of transactions?

SELECT top 1
prod_cat, ROUND(SUM(CAST(total_amt AS float)),2) AS TOTAL 
FROM
prod_cat_info A
INNER JOIN Transactions B ON A.prod_cat_code = B.prod_cat_code AND A.prod_sub_cat_code = B.prod_subcat_code
WHERE CAST(total_amt AS float)<0 AND
CONVERT(date, TRAN_DATE, 105) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,TRAN_DATE,105)) FROM TRANSACTIONS)) 
	 AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,105)) FROM TRANSACTIONS)
GROUP BY
prod_cat
order by
TOTAL DESC;

--Q13. Which store-type sells the max products, by the value of sales amount and by quantity sold?

SELECT
store_type, SUM(cast(total_amt as float)) as total_sales, COUNT(qty) as qty 
FROM
Transactions A
INNER JOIN prod_cat_info B ON A.prod_cat_code = b.prod_cat_code and A.prod_subcat_code = b.prod_sub_cat_code
group by
store_type
order by
total_sales desc, qty desc

--Q14. What are the categories for which average revenue is above the overall average?

select
prod_cat, round(AVG(cast(total_amt as float)),2) as avg_revenue
from 
Transactions A
inner join prod_cat_info B on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
group by
prod_cat
having
 round(AVG(cast(total_amt as float)),2)>(select round(avg(cast(total_amt as float)),2) from Transactions)

 --Q15. Find the avg and total revenue by each sub category for the categories which are among the top 5 category in terms of item sold?

 select
prod_cat, prod_subcat,ROUND(SUM(CAST(total_amt as float)),2) AS TOT_REVENUE, round(AVG(cast(total_amt as float)),2) as AVG_REVENUE
from 
Transactions A
inner join prod_cat_info B on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
where
prod_cat in (select top 5
prod_cat
from
Transactions A
inner join prod_cat_info B on A.prod_cat_code = B.prod_cat_code and A.prod_subcat_code = B.prod_sub_cat_code
group by
prod_cat 
order by
count(qty) desc)
GROUP BY
prod_cat, prod_subcat


